version: '3.8'

services:
  api:
    depends_on:
      api-postgres:
        condition: service_healthy
    image: simple-flask
    build:
      context: simple_flask
      dockerfile: ./Dockerfile
#    env_file:
#      - .env
    ports:
      - 5001:5000
    volumes:
      - ./simple_flask/app:/app
    stdin_open: true
    tty: true
  api-postgres:
    image: postgres:11.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 456124
      POSTGRES_DB: crud_stocks
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pg-data:
